# Development profile (dev) Configuration:

######################
# Persistence :: Dev #
######################

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:kogito;NON_KEYWORDS=VALUE,KEY
spring.datasource.username=kogito
spring.datasource.password=kogito

#################################
# Event-driven Workflows :: Dev #
#################################

# spring.kafka.bootstrap-servers=localhost:9092

############
# Services #
############

# These properties are residual from Distributed Architecture, where Data-Index, Data-Audit,
# and Jobs Service are external to the Business Service.
#
# They are still necessary but won't be anymore in future BAMOE releases.
kogito.service.url=http://${server.address}:${server.port}${server.servlet.context-path}
kogito.jobs-service.url=http://${server.address}:${server.port}${server.servlet.context-path}
kogito.data-index.url=http://${server.address}:${server.port}${server.servlet.context-path}

################
# Misc. :: Dev #
################

## GraphiQL Console
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=${server.servlet.context-path}/graphiql
spring.graphql.schema.printer.enabled=true

bamoe.web-console.enabled=true

################
# CORS :: Dev  #
################

# In development mode, allow all origins for easier local testing.
# Override this in production with specific allowed origins.
bamoe.cors.allowed-origin-patterns=*