kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ $.devDeployment.uniqueName }}
  namespace: ${{ $.devDeployment.kubernetes.namespace }}
  labels:
    app: ${{ $.devDeployment.uniqueName }}
    app.kubernetes.io/component: ${{ $.devDeployment.uniqueName }}
    app.kubernetes.io/instance: ${{ $.devDeployment.uniqueName }}
    app.kubernetes.io/name: ${{ $.devDeployment.uniqueName }}
    app.kubernetes.io/part-of: ${{ $.devDeployment.uniqueName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ $.devDeployment.uniqueName }}
  template:
    metadata:
      labels:
        app: ${{ $.devDeployment.uniqueName }}
        deploymentconfig: ${{ $.devDeployment.uniqueName }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - s390x
      containers:
        - name: ${{ $.devDeployment.uniqueName }}
          image: quay.io/bamoe/canvas-dev-deployment-base:9.4.2-ibm-0002-jdk21
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2048Mi"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DEV_DEPLOYMENT__UPLOAD_SERVICE_API_KEY
              value: ${{ $.devDeployment.uploadService.apiKey }}
