package org.acme.wrapper.assignment;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;

/**
 * Assignment memory per (workflowName, taskName, fieldName, scope):
 * <ul>
 *   <li>scope = an <b>instanceId</b> → "who was assigned this task in this instance"
 *       (used by the {@code LAST_ASSIGN_TO_*} strategies; recorded for every resolved
 *       assignment, whatever the strategy).</li>
 *   <li>scope = {@link #GLOBAL_SCOPE} → the workflow+task-wide {@code ROUND_ROBIN}
 *       rotation cursor, shared across all instances.</li>
 * </ul>
 *
 * <p>Backed by {@code JdbcTemplate}; the table is created at startup with
 * dialect-appropriate DDL (H2/PostgreSQL/Oracle 12c+). A pre-existing table in an old
 * shape (no {@code instance_id} column) is dropped and recreated — it only ever held
 * rotation cursors / sticky picks, which rebuild naturally.</p>
 */
@Repository
public class LastAssignmentStore {

    /** Scope marker for workflow+task-wide rows (Oracle treats '' as NULL, so a real value). */
    public static final String GLOBAL_SCOPE = "ALL";

    private static final Logger log = LoggerFactory.getLogger(LastAssignmentStore.class);
    private static final String TABLE = "last_assignment";

    private final JdbcTemplate jdbc;

    public LastAssignmentStore(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    void createTableIfMissing() {
        jdbc.execute((ConnectionCallback<Void>) conn -> {
            if (tableExists(conn)) {
                if (hasColumn(conn, "instance_id")) {
                    return null;
                }
                // Old shape — replace; the rows were only rotation cursors / sticky
                // picks and rebuild on the next assignment.
                try (Statement st = conn.createStatement()) {
                    st.execute("DROP TABLE " + TABLE);
                    log.info("Dropped old-shape table {} (no instance_id column)", TABLE);
                }
            }
            boolean oracle = isOracle(conn);
            String idType = oracle ? "NUMBER(19)" : "BIGINT";
            String str = oracle ? "VARCHAR2" : "VARCHAR";
            String ddl = "CREATE TABLE " + TABLE + " ("
                    + "id " + idType + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "workflow_name " + str + "(255) NOT NULL, "
                    + "task_name " + str + "(255) NOT NULL, "
                    + "field_name " + str + "(255) NOT NULL, "
                    + "instance_id " + str + "(255) NOT NULL, "
                    + "assignee_value " + str + "(4000), "
                    + "updated_by " + str + "(255), "
                    + "updated_at TIMESTAMP, "
                    + "CONSTRAINT uq_last_assignment UNIQUE (workflow_name, task_name, field_name, instance_id))";
            try (Statement st = conn.createStatement()) {
                st.execute(ddl);
                log.info("Created table {}", TABLE);
            } catch (SQLException e) {
                // Another instance may have created it concurrently — tolerate it.
                if (tableExists(conn)) {
                    log.debug("Table {} already exists (created concurrently)", TABLE);
                } else {
                    throw e;
                }
            }
            return null;
        });
    }

    private boolean isOracle(Connection conn) throws SQLException {
        String product = conn.getMetaData().getDatabaseProductName();
        return product != null && product.toLowerCase().contains("oracle");
    }

    private boolean tableExists(Connection conn) throws SQLException {
        DatabaseMetaData md = conn.getMetaData();
        // Unquoted identifiers fold to lower-case (PostgreSQL) or upper-case (H2, Oracle).
        for (String name : new String[] {TABLE, TABLE.toUpperCase()}) {
            try (ResultSet rs = md.getTables(null, null, name, new String[] {"TABLE"})) {
                if (rs.next()) {
                    return true;
                }
            }
        }
        return false;
    }

    private boolean hasColumn(Connection conn, String column) throws SQLException {
        DatabaseMetaData md = conn.getMetaData();
        for (String table : new String[] {TABLE, TABLE.toUpperCase()}) {
            for (String col : new String[] {column, column.toUpperCase()}) {
                try (ResultSet rs = md.getColumns(null, null, table, col)) {
                    if (rs.next()) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    /**
     * The remembered assignee for this workflow + task + field within {@code scope}
     * (an instanceId, or {@link #GLOBAL_SCOPE} for the rotation cursor).
     */
    public Optional<String> findAssignee(String workflowName, String taskName, String fieldName, String scope) {
        List<String> values = jdbc.query(
                "SELECT assignee_value FROM last_assignment "
                        + "WHERE workflow_name = ? AND task_name = ? AND field_name = ? AND instance_id = ?",
                (rs, rowNum) -> rs.getString(1), workflowName, taskName, fieldName, scope);
        return values.isEmpty() ? Optional.empty() : Optional.ofNullable(values.get(0));
    }

    public void upsert(String workflowName, String taskName, String fieldName, String scope,
                       String assigneeValue, String updatedBy) {
        Timestamp now = Timestamp.from(Instant.now());
        int updated = jdbc.update(
                "UPDATE last_assignment SET assignee_value = ?, updated_by = ?, updated_at = ? "
                        + "WHERE workflow_name = ? AND task_name = ? AND field_name = ? AND instance_id = ?",
                assigneeValue, updatedBy, now, workflowName, taskName, fieldName, scope);
        if (updated == 0) {
            jdbc.update(
                    "INSERT INTO last_assignment "
                            + "(workflow_name, task_name, field_name, instance_id, assignee_value, updated_by, updated_at) "
                            + "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    workflowName, taskName, fieldName, scope, assigneeValue, updatedBy, now);
        }
    }
}
