package org.acme.wrapper.assignment;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;

/**
 * Stores/reads the last assignee per (workflowId, fieldName) for the
 * {@code LAST_ASSIGN_TO_*} strategies. Backed by {@code JdbcTemplate}; the table is
 * created at startup (independent of Kogito's JPA unit and kie.flyway). Existence is
 * checked via {@code DatabaseMetaData} (portable), and the DDL is adapted per database
 * so it works on H2, PostgreSQL and Oracle (12c+).
 */
@Repository
public class LastAssignmentStore {

    private static final Logger log = LoggerFactory.getLogger(LastAssignmentStore.class);
    private static final String TABLE = "last_assignment";

    private final JdbcTemplate jdbc;

    public LastAssignmentStore(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    void createTableIfMissing() {
        jdbc.execute((ConnectionCallback<Void>) conn -> {
            if (tableExists(conn)) {
                return null;
            }
            boolean oracle = isOracle(conn);
            String idType = oracle ? "NUMBER(19)" : "BIGINT";
            String str = oracle ? "VARCHAR2" : "VARCHAR";
            String ddl = "CREATE TABLE " + TABLE + " ("
                    + "id " + idType + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "workflow_id " + str + "(255) NOT NULL, "
                    + "field_name " + str + "(255) NOT NULL, "
                    + "assignee_value " + str + "(4000), "
                    + "updated_by " + str + "(255), "
                    + "updated_at TIMESTAMP, "
                    + "CONSTRAINT uq_last_assignment UNIQUE (workflow_id, field_name))";
            try (Statement st = conn.createStatement()) {
                st.execute(ddl);
                log.info("Created table {}", TABLE);
            } catch (SQLException e) {
                // Another instance may have created it concurrently — tolerate it.
                if (tableExists(conn)) {
                    log.debug("Table {} already exists (created concurrently)", TABLE);
                } else {
                    throw e;
                }
            }
            return null;
        });
    }

    private boolean isOracle(Connection conn) throws SQLException {
        String product = conn.getMetaData().getDatabaseProductName();
        return product != null && product.toLowerCase().contains("oracle");
    }

    private boolean tableExists(Connection conn) throws SQLException {
        DatabaseMetaData md = conn.getMetaData();
        // Unquoted identifiers fold to lower-case (PostgreSQL) or upper-case (H2, Oracle).
        for (String name : new String[] {TABLE, TABLE.toUpperCase()}) {
            try (ResultSet rs = md.getTables(null, null, name, new String[] {"TABLE"})) {
                if (rs.next()) {
                    return true;
                }
            }
        }
        return false;
    }

    public Optional<String> findAssignee(String workflowId, String fieldName) {
        List<String> values = jdbc.query(
                "SELECT assignee_value FROM last_assignment WHERE workflow_id = ? AND field_name = ?",
                (rs, rowNum) -> rs.getString(1), workflowId, fieldName);
        return values.isEmpty() ? Optional.empty() : Optional.ofNullable(values.get(0));
    }

    public void upsert(String workflowId, String fieldName, String assigneeValue, String updatedBy) {
        Timestamp now = Timestamp.from(Instant.now());
        int updated = jdbc.update(
                "UPDATE last_assignment SET assignee_value = ?, updated_by = ?, updated_at = ? "
                        + "WHERE workflow_id = ? AND field_name = ?",
                assigneeValue, updatedBy, now, workflowId, fieldName);
        if (updated == 0) {
            jdbc.update(
                    "INSERT INTO last_assignment (workflow_id, field_name, assignee_value, updated_by, updated_at) "
                            + "VALUES (?, ?, ?, ?, ?)",
                    workflowId, fieldName, assigneeValue, updatedBy, now);
        }
    }
}
