package org.acme.wrapper.comments;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;

/**
 * Custom comments per (instanceId, taskId), independent of the engine's own comment
 * subsystem. Backed by {@code JdbcTemplate}; the table is created at startup with
 * dialect-appropriate DDL (H2/PostgreSQL/Oracle 12c+). The text column is deliberately
 * named {@code comment_text} — {@code COMMENT} is reserved in Oracle.
 */
@Repository
public class TaskCommentStore {

    private static final Logger log = LoggerFactory.getLogger(TaskCommentStore.class);
    private static final String TABLE = "wrapper_task_comments";

    private final JdbcTemplate jdbc;

    public TaskCommentStore(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    void createTableIfMissing() {
        jdbc.execute((ConnectionCallback<Void>) conn -> {
            if (tableExists(conn)) {
                return null;
            }
            boolean oracle = isOracle(conn);
            String idType = oracle ? "NUMBER(19)" : "BIGINT";
            String str = oracle ? "VARCHAR2" : "VARCHAR";
            String ddl = "CREATE TABLE " + TABLE + " ("
                    + "id " + idType + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "instance_id " + str + "(255) NOT NULL, "
                    + "task_id " + str + "(255) NOT NULL, "
                    + "task_name " + str + "(255), "
                    + "comment_text " + str + "(4000), "
                    + "comment_by " + str + "(255) NOT NULL, "
                    + "comment_at TIMESTAMP)";
            try (Statement st = conn.createStatement()) {
                st.execute(ddl);
                st.execute("CREATE INDEX idx_" + TABLE + "_iid ON " + TABLE + "(instance_id)");
                log.info("Created table {}", TABLE);
            } catch (SQLException e) {
                if (tableExists(conn)) {
                    log.debug("Table {} already exists (created concurrently)", TABLE);
                } else {
                    throw e;
                }
            }
            return null;
        });
    }

    private boolean isOracle(Connection conn) throws SQLException {
        String product = conn.getMetaData().getDatabaseProductName();
        return product != null && product.toLowerCase().contains("oracle");
    }

    private boolean tableExists(Connection conn) throws SQLException {
        DatabaseMetaData md = conn.getMetaData();
        for (String name : new String[] {TABLE, TABLE.toUpperCase()}) {
            try (ResultSet rs = md.getTables(null, null, name, new String[] {"TABLE"})) {
                if (rs.next()) {
                    return true;
                }
            }
        }
        return false;
    }

    public long insert(String instanceId, String taskId, String taskName, String commentText, String commentBy) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        Timestamp now = Timestamp.from(Instant.now());
        jdbc.update(conn -> {
            PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO " + TABLE + " (instance_id, task_id, task_name, comment_text, comment_by, comment_at) "
                            + "VALUES (?, ?, ?, ?, ?, ?)",
                    new String[] {"id"});
            ps.setString(1, instanceId);
            ps.setString(2, taskId);
            ps.setString(3, taskName);
            ps.setString(4, commentText);
            ps.setString(5, commentBy);
            ps.setTimestamp(6, now);
            return ps;
        }, keyHolder);
        Number key = keyHolder.getKey();
        return (key == null) ? -1 : key.longValue();
    }

    public int update(long id, String commentText) {
        return jdbc.update("UPDATE " + TABLE + " SET comment_text = ?, comment_at = ? WHERE id = ?",
                commentText, Timestamp.from(Instant.now()), id);
    }

    public int delete(long id) {
        return jdbc.update("DELETE FROM " + TABLE + " WHERE id = ?", id);
    }

    public Optional<Map<String, Object>> findById(long id) {
        List<Map<String, Object>> rows = jdbc.query(
                "SELECT id, instance_id, task_id, task_name, comment_text, comment_by, comment_at FROM " + TABLE
                        + " WHERE id = ?",
                (rs, i) -> mapRow(rs), id);
        return rows.isEmpty() ? Optional.empty() : Optional.of(rows.get(0));
    }

    /** Newest first, with optional taskName/commentBy filters and OFFSET/FETCH pagination. */
    public List<Map<String, Object>> find(String instanceId, String taskName, String commentBy,
                                          int offset, int limit) {
        StringBuilder sql = new StringBuilder(
                "SELECT id, instance_id, task_id, task_name, comment_text, comment_by, comment_at FROM " + TABLE
                        + " WHERE instance_id = ?");
        List<Object> args = new ArrayList<>();
        args.add(instanceId);
        appendFilters(sql, args, taskName, commentBy);
        sql.append(" ORDER BY comment_at DESC, id DESC OFFSET ? ROWS FETCH NEXT ? ROWS ONLY");
        args.add(offset);
        args.add(limit);
        return jdbc.query(sql.toString(), (rs, i) -> mapRow(rs), args.toArray());
    }

    public long count(String instanceId, String taskName, String commentBy) {
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) FROM " + TABLE + " WHERE instance_id = ?");
        List<Object> args = new ArrayList<>();
        args.add(instanceId);
        appendFilters(sql, args, taskName, commentBy);
        Long count = jdbc.queryForObject(sql.toString(), Long.class, args.toArray());
        return (count == null) ? 0 : count;
    }

    private void appendFilters(StringBuilder sql, List<Object> args, String taskName, String commentBy) {
        if (taskName != null && !taskName.isBlank()) {
            sql.append(" AND task_name = ?");
            args.add(taskName.trim());
        }
        if (commentBy != null && !commentBy.isBlank()) {
            sql.append(" AND comment_by = ?");
            args.add(commentBy.trim());
        }
    }

    private Map<String, Object> mapRow(ResultSet rs) throws SQLException {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("id", rs.getLong("id"));
        row.put("instanceId", rs.getString("instance_id"));
        row.put("taskId", rs.getString("task_id"));
        row.put("taskName", rs.getString("task_name"));
        row.put("comment", rs.getString("comment_text"));
        row.put("commentBy", rs.getString("comment_by"));
        row.put("commentAt", rs.getTimestamp("comment_at"));
        return row;
    }
}
