package org.acme.wrapper.decisions;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import jakarta.annotation.PostConstruct;

/**
 * Decision configuration per (workflowName, taskName): which output variable carries the
 * task's decision and which values are allowed. When a row exists, completing the task
 * requires that variable with one of the allowed values; without a row there is no
 * validation. Backed by {@code JdbcTemplate}; the table is created at startup with
 * dialect-appropriate DDL (H2/PostgreSQL/Oracle 12c+).
 */
@Repository
public class DecisionConfigStore {

    private static final Logger log = LoggerFactory.getLogger(DecisionConfigStore.class);
    private static final String TABLE = "wrapper_task_decisions";

    private final JdbcTemplate jdbc;

    public DecisionConfigStore(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    void createTableIfMissing() {
        jdbc.execute((ConnectionCallback<Void>) conn -> {
            if (tableExists(conn)) {
                return null;
            }
            boolean oracle = isOracle(conn);
            String idType = oracle ? "NUMBER(19)" : "BIGINT";
            String str = oracle ? "VARCHAR2" : "VARCHAR";
            String ddl = "CREATE TABLE " + TABLE + " ("
                    + "id " + idType + " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "workflow_name " + str + "(255) NOT NULL, "
                    + "task_name " + str + "(255) NOT NULL, "
                    + "variable_name " + str + "(255) NOT NULL, "
                    + "allowed_values " + str + "(4000) NOT NULL, "
                    + "updated_by " + str + "(255), "
                    + "updated_at TIMESTAMP, "
                    + "CONSTRAINT uq_wrapper_task_decisions UNIQUE (workflow_name, task_name))";
            try (Statement st = conn.createStatement()) {
                st.execute(ddl);
                log.info("Created table {}", TABLE);
            } catch (SQLException e) {
                if (tableExists(conn)) {
                    log.debug("Table {} already exists (created concurrently)", TABLE);
                } else {
                    throw e;
                }
            }
            return null;
        });
    }

    private boolean isOracle(Connection conn) throws SQLException {
        String product = conn.getMetaData().getDatabaseProductName();
        return product != null && product.toLowerCase().contains("oracle");
    }

    private boolean tableExists(Connection conn) throws SQLException {
        DatabaseMetaData md = conn.getMetaData();
        for (String name : new String[] {TABLE, TABLE.toUpperCase()}) {
            try (ResultSet rs = md.getTables(null, null, name, new String[] {"TABLE"})) {
                if (rs.next()) {
                    return true;
                }
            }
        }
        return false;
    }

    /** The decision config for this workflow + task, if any. */
    public Optional<Map<String, Object>> find(String workflowName, String taskName) {
        List<Map<String, Object>> rows = jdbc.query(
                "SELECT workflow_name, task_name, variable_name, allowed_values FROM " + TABLE
                        + " WHERE workflow_name = ? AND task_name = ?",
                (rs, i) -> mapRow(rs), workflowName, taskName);
        return rows.isEmpty() ? Optional.empty() : Optional.of(rows.get(0));
    }

    /** All decision configs of a workflow. */
    public List<Map<String, Object>> findByWorkflow(String workflowName) {
        return jdbc.query(
                "SELECT workflow_name, task_name, variable_name, allowed_values FROM " + TABLE
                        + " WHERE workflow_name = ? ORDER BY task_name",
                (rs, i) -> mapRow(rs), workflowName);
    }

    public void upsert(String workflowName, String taskName, String variableName,
                       List<String> allowedValues, String updatedBy) {
        String csv = String.join(",", allowedValues);
        Timestamp now = Timestamp.from(Instant.now());
        int updated = jdbc.update(
                "UPDATE " + TABLE + " SET variable_name = ?, allowed_values = ?, updated_by = ?, updated_at = ? "
                        + "WHERE workflow_name = ? AND task_name = ?",
                variableName, csv, updatedBy, now, workflowName, taskName);
        if (updated == 0) {
            jdbc.update(
                    "INSERT INTO " + TABLE
                            + " (workflow_name, task_name, variable_name, allowed_values, updated_by, updated_at) "
                            + "VALUES (?, ?, ?, ?, ?, ?)",
                    workflowName, taskName, variableName, csv, updatedBy, now);
        }
    }

    /** @return true when a config existed and was removed. */
    public boolean delete(String workflowName, String taskName) {
        return jdbc.update("DELETE FROM " + TABLE + " WHERE workflow_name = ? AND task_name = ?",
                workflowName, taskName) > 0;
    }

    private Map<String, Object> mapRow(ResultSet rs) throws SQLException {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("workflowName", rs.getString("workflow_name"));
        row.put("taskName", rs.getString("task_name"));
        row.put("variableName", rs.getString("variable_name"));
        List<String> values = new ArrayList<>();
        for (String v : rs.getString("allowed_values").split(",")) {
            if (!v.isBlank()) {
                values.add(v.trim());
            }
        }
        row.put("allowedValues", values);
        return row;
    }
}
